[package]
license = "Apache-2.0"
name = "valayam-core"
version.workspace = true
edition.workspace = true

[dependencies]
valayam-models = { workspace = true }
valayam-network = { workspace = true }
valayam-engine = { workspace = true }
valayam-proto = { workspace = true }
valayam-core-net = { path = "../valayam-core-net" }
valayam-reporter = { path = "../valayam-reporter" }
valayam-crawler = { path = "../valayam-crawler" }
valayam-threatintel = { path = "../valayam-threatintel" }
valayam-proxy = { path = "../valayam-proxy" }
valayam-schema-drift = { path = "../valayam-schema-drift" }
valayam-oob = { path = "../valayam-oob" }
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }
tokio-util = { version = "0.7", features = ["rt"] }
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
reqwest = { workspace = true }
rhai = { workspace = true }
regex = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }
base64 = { workspace = true }
md5 = { workspace = true }
sha2 = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
governor = { workspace = true }
url.workspace = true
hickory-resolver = { workspace = true }
x509-parser = { workspace = true }
rustls-pemfile = { workspace = true }
rustls.workspace = true
tokio-rustls = { workspace = true }
rand = { workspace = true }
hmac = { workspace = true }
tracing = "0.1.44"
tracing-opentelemetry = "0.33"
http = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
scraper = { workspace = true }
urlencoding = "2.1.3"
wasmparser = { workspace = true }
sourcemap = { workspace = true }
zip.workspace = true
toml = { workspace = true }
lazy_static = { workspace = true }
wasmtime = "43.0.2"
wasmtime-wasi = "47.0.3"
uuid = { version = "1.24.0", features = ["v4"] }
dirs = "6.0.0"
ed25519-dalek = { version = "3.0.0", features = ["rand_core"] }
rand_core = { version = "0.6.4", features = ["std"] }
notify = "8.2.0"
opentelemetry = { version = "0.32.0", features = ["trace"] }
petgraph = { version = "0.8.3", features = ["serde-1"] }
colored = "3.1.1"
hex = { workspace = true }
axum = "0.8"
jsonwebtoken = "11.0"
dashmap = "6.2.1"
rcgen = "0.14"
hyper = { version = "1.10", features = ["full"] }
time = "0.3.54"
valayam-common = { version = "0.1.0", path = "../valayam-common" }
[features]
sarif = []

[build-dependencies]

[[bench]]
name = "crawler_bench"
harness = false

[dev-dependencies]
criterion = { version = "0.8", features = ["async_tokio"] }
mockito = "1.7.2"
tempfile = { workspace = true }
wat = "1.253.0"
valayam-crypto = { path = "../valayam-crypto" }
