[package]
license = "Apache-2.0"
name = "valayam-tests"
version.workspace = true
edition.workspace = true

[dependencies]
valayam-api = { path = "../valayam-api" }
valayam-core = { path = "../valayam-core" }
valayam-cli = { path = "../valayam-cli" }

valayam-engine = { path = "../valayam-engine" }
valayam-models = { path = "../valayam-models" }
valayam-common = { path = "../valayam-common" }
tokio = { workspace = true, features = ["full"] }
axum = "0.8"
reqwest = { workspace = true }
tracing = "0.1"
assert_cmd = "2.2.2"
predicates = "3.1.4"
tokio-util = "0.7.19"
uuid = { version = "1.24.0", features = ["v4"] }
valayam-config = { workspace = true }
