use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, DeriveInput};

/// Automatically generates a JSON schema for a Valayam WASM plugin configuration.
///
/// When this macro is applied to a configuration struct, it derives `schemars::JsonSchema`
/// and provides an `export_schema()` function that returns the serialized JSON Schema.
#[proc_macro_derive(ValayamConfig)]
pub fn valayam_config_derive(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let name = &input.ident;

    let expanded = quote! {
        impl #name {
            /// Automatically generated by `#[derive(ValayamConfig)]`.
            /// Returns the JSON Schema for this plugin's configuration.
            pub fn export_schema() -> String {
                let schema = valayam_plugin_sdk::schemars::schema_for!(#name);
                valayam_plugin_sdk::serde_json::to_string_pretty(&schema).unwrap()
            }
        }
    };

    TokenStream::from(expanded)
}
