[book]
authors = ["Valayam Contributors"]
language = "en"
src = "src"
title = "Valayam Documentation"

[build]
build-dir = "book"
create-missing = false

[output.html]
git-repository-url = "https://github.com/techken-in/valayam"
edit-url-template = "https://github.com/techken-in/valayam/edit/main/docs/{path}"
mathjax-support = true
