//! Safe panic-boundary wrapper for plugin execution.
//!
//! # Why this exists
//! Rust's `catch_unwind` requires `UnwindSafe` on the future it catches. Plugin
//! futures capture `&ScanContext` (all fields are `Arc`, `mpsc::Sender`, or
//! `CancellationToken` — each is `UnwindSafe` on its own) and return
//! `PluginOutcome` (owned data, `UnwindSafe`). However, the async state machine
//! generated by the compiler may hold internal references that the trait solver
//! cannot prove are unwind-safe, producing a compile error.
//!
//! # Design
//! `SafePluginFuture` wraps the inner future in `AssertUnwindSafe`, documenting
//! the safety contract in one place rather than sprinkling `AssertUnwindSafe`
//! throughout the executor. This makes the assertion **auditable**.
//!
//! # Safety contract
//! The inner future must only capture:
//! - `&ScanContext` (all fields are `Arc`, `mpsc::Sender`, or `CancellationToken`)
//! - `&dyn ScanPlugin` (behind `Arc`, no interior mutability)
//! - Owned values that implement `UnwindSafe`
//!
//! It must NOT capture:
//! - `&mut` references to non-`UnwindSafe` types
//! - `MutexGuard` or `RwLockReadGuard` (use `Arc` + lock inside the future instead)

use std::panic::AssertUnwindSafe;

/// A future wrapper for plugin execution that asserts unwind safety.
///
/// # Safety
/// The inner future must only capture:
/// - `&ScanContext` (all fields are `Arc`, `mpsc::Sender`, or `CancellationToken`)
/// - `&dyn ScanPlugin` (behind `Arc`, no interior mutability)
/// - Owned values that implement `UnwindSafe`
///
/// It must NOT capture:
/// - `&mut` references to non-`UnwindSafe` types
/// - `MutexGuard` or `RwLockReadGuard` (use `Arc` + lock inside the future instead)
pub struct SafePluginFuture<F>(pub AssertUnwindSafe<F>);

impl<F> SafePluginFuture<F> {
    /// Create a new safe plugin future.
    ///
    /// # Safety
    /// Caller must ensure the inner future meets the safety contract above.
    #[allow(unused)]
    pub unsafe fn new(future: F) -> Self {
        Self(AssertUnwindSafe(future))
    }
}
