# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: valayam.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'valayam.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rvalayam.proto\x12\x07valayam\"8\n\x0bScanRequest\x12\x15\n\rtemplate_yaml\x18\x01 \x01(\t\x12\x12\n\ntarget_url\x18\x02 \x01(\t\"%\n\x0cScanResponse\x12\x15\n\rfindings_json\x18\x01 \x03(\t2>\n\x07Scanner\x12\x33\n\x04Scan\x12\x14.valayam.ScanRequest\x1a\x15.valayam.ScanResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'valayam_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCANREQUEST']._serialized_start=26
  _globals['_SCANREQUEST']._serialized_end=82
  _globals['_SCANRESPONSE']._serialized_start=84
  _globals['_SCANRESPONSE']._serialized_end=121
  _globals['_SCANNER']._serialized_start=123
  _globals['_SCANNER']._serialized_end=185
# @@protoc_insertion_point(module_scope)
