[package]
license = "Apache-2.0"
name = "valayam-cli"
version.workspace = true
edition.workspace = true

[dependencies]
tokio-util = { version = "0.7", features = ["rt"] }
tokio = { workspace = true }
clap = { workspace = true }
walkdir.workspace = true
valayam-core = { path = "../valayam-core" }
valayam-core-net = { path = "../valayam-core-net" }
valayam-engine = { workspace = true }
valayam-telemetry = { path = "../valayam-telemetry" }
valayam-crypto = { path = "../valayam-crypto" }
valayam-state = { path = "../valayam-state" }
valayam-reporter = { path = "../valayam-reporter" }
valayam-proxy = { path = "../valayam-proxy" }
valayam-oob = { path = "../valayam-oob" }
valayam-config = { path = "../valayam-config" }
valayam-models = { workspace = true }
valayam-network = { workspace = true }
valayam-common = { path = "../valayam-common" }
indicatif = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
serde_json = { workspace = true }
tracing = "0.1.44"
tonic = { workspace = true }
prost = { workspace = true }
rcgen = "0.12"
tokio-rustls = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
dirs = "5.0"
time = "0.3"
reqwest = { workspace = true }
hyper = { version = "0.14", features = ["full"] }
serde_yaml = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
genpdf = "0.2.0"
zip.workspace = true
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
rand.workspace = true
colored = "3.1.1"
chrono = { workspace = true }
hex.workspace = true
hmac = "0.12"
sha2 = "0.10"
uuid = { version = "1.24.0", features = ["v4"] }
dotenvy = "0.15"
valayam-api = { version = "0.1.0", path = "../valayam-api" }
[dev-dependencies]
assert_cmd = "2.2.2"
predicates = "3.1.4"
tempfile.workspace = true
